language: python
matrix:
  include:
  - env: TARGET=python2
  - env: TARGET=python35
  - env: TARGET=python36
  - env: TARGET=pep8
sudo: required
services:
- docker
before_install:
- true
install:
- docker build . -t ${TARGET} -f .travis/${TARGET}.docker
before_script:
- true
script:
- true
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: 0YLnlpZqPUnap1ymR+MMuZgLUl/eZDfYgZwSz/Ll1DWsS7ntWZyHafd5lQD6jOm60QwvLdURKrf5zPocowY2e6/XED+26kPSJWQf1F5hK8fzrs3TtYQM9karl1JaxO1GiNkLqfEGoN2fyCsmEt7xCSTxuzmNhx0J7ioV0+htteX5QjQ8XUYJ6oDCYS2EC59Ncs4t891mWMQm7FFGOvj1EuYjyPpHc4iU4T7GV7DkleqU/91q3kch74sN7qeF3chKxgL3Hd5DldA19GRin/ZXcx8SQspzgvqTKJ/JG5mS4CsWyzoMXnvngreqB0Yy5+mQOLqaUArsXnZm6pxOcYC/0ABK4xpqU3G/R67sll4qSJ4ybsYRWqS2GuDCNJXirsbeOlLtt+WtpVo0jglS8uQ4y6zX3ldodZfbsL7+rV63YT2YAf417vAMA42rAa9mNm0P+hmF3aHHGlgEfYNd1fEsuxY1WS8XsyLV/Q1DMo1+pvbyd10HP1VwXh7u3lEbf+tYytOQxvYROAVnbwT2+8KgQvBYQW6fGa2MHs5d8GodxJulutKaGHdaoGcaNZYnEvrElJfPWsYvbazJhLALM3hBeCIFPyu436AlkEk99115Nb7nrLprHf9f42Y17ALydc8F6E2E3L/iH1hlbhAFxzPbi1PBQSUDWdS8KmYELXmUtJA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ska-sa/xarray-fits
