name: Ubuntu CI

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
  schedule:
    - cron: '30 2 * * 1,4' # Every Monday and Thursday @ 2h30am UTC

jobs:
  check_skip:
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
    steps:
      - run: |
          cat <<'MESSAGE'
          github.event_name: ${{ toJson(github.event_name) }}
          github.event:
          ${{ toJson(github.event) }}
          MESSAGE
  test:
    needs: check_skip
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install xarray-fits
        run: pip install .[testing]

      - name: Test xarray-fits
        run: py.test -s -vvv tests

      # - name: Debug with tmate on failure
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3

  upload-to-test-pypi:
    name: Upload release to Test PyPI
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: release-test
    permissions:
      id-token: write
    steps:
     - name: Checkout source
       uses: actions/checkout@v6
       with:
          fetch-depth: 1

     - name: Build distributions
       run: |
        pip install -U pip build
        python -m build --sdist --wheel

     - name: Publish package distributions to Test PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
       continue-on-error: true

  upload-to-pypi:
    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
     - name: Checkout source
       uses: actions/checkout@v6
       with:
          fetch-depth: 1

     - name: Build distributions
       run: |
        pip install -U pip build
        python -m build --sdist --wheel

     - name: Publish package distributions to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
